### PR TITLE
fix secrets

### PR DESCRIPTION
**Pull request by dagl**
### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [x] (Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.

### CODE REVIEW

**Comment by glpatcern** [comment]
Thanks!

**Comment by dagl** [comment]
@glpatcern how do I properly test if the wopi is working correcly? https://cs3mesh.softwaremind.com/wopi is this enough, or should I test collabora/codimd as well?

**Comment by glpatcern** [comment]
@dagl you should first try and deploy release 7.5.5 as older WOPI server releases do not work with latest Reva. Then it sould be tested with Collabora, yes, and as an intermediate step you could execute the WOPI server testsuite to validate that the WOPI server can talk to Reva.

If you want we can discuss more details over e.g. [gitter.im/](https://gitter.im/cs3org/wopiserver), let me know.

**Comment by dagl** [comment]
> @dagl you should first try and deploy release 7.5.5 as older WOPI server releases do not work with latest Reva. Then it sould be tested with Collabora, yes, and as an intermediate step you could execute the WOPI server testsuite to validate that the WOPI server can talk to Reva.
> 
> If you want we can discuss more details over e.g. [gitter.im/](https://gitter.im/cs3org/wopiserver), let me know.

I did deploy version  7.5, but I didn't deploy the latest Reva yet. What testsuite are you talking about? And what's you handle on Gitter?

**Comment by glpatcern** [comment]
> I did deploy version 7.5, but I didn't deploy the latest Reva yet.

OK, but from what I saw at https://cs3mesh.softwaremind.com/wopi it's v6.7

> What testsuite are you talking about? And what's you handle on Gitter?

The WOPI testsuite at https://github.com/cs3org/wopiserver/#unit-testing. My gitter handle is the GitHub one.

**Comment by dagl** [comment]
> > I did deploy version 7.5, but I didn't deploy the latest Reva yet.
> 
> OK, but from what I saw at https://cs3mesh.softwaremind.com/wopi it's v6.7

I see, that's weird.

> > What testsuite are you talking about? And what's you handle on Gitter?
> 
> The WOPI testsuite at https://github.com/cs3org/wopiserver/#unit-testing. My gitter handle is the GitHub one.

Ok, I'll check these tests

**Pull request merged**
