### PR TITLE
upgrade version in values.yaml

### PR DESCRIPTION
**Pull request by dagl**
### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [x] (Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.

### CODE REVIEW

**Comment by dagl** [comment]
@glpatcern the version wasn't upgraded in values, that's why helm deployed 6.7 earlier

**Comment by dagl** [comment]
@glpatcern About tests, I tried running them from my laptop without even configuring Reva or Wopi adresses and more than half of them passed, so I'm not sure if they are up to date. Also, I'm not sure how to even configure them correctly

**Comment by glpatcern** [comment]
> @glpatcern About tests, I tried running them from my laptop without even configuring Reva or Wopi adresses and more than half of them passed, so I'm not sure if they are up to date. Also, I'm not sure how to even configure them correctly

In the link I provided you'll see that by default they run against local storage (and they're now integrated in the GitHub CI, see e.g. https://github.com/cs3org/wopiserver/runs/5394336262, so it's fair they pass. You should try and run them against Reva.

As for the version, yeah this was the latest at the time I started to update the charts, but better to push to a more recent one.

**Comment by dagl** [comment]
> > @glpatcern About tests, I tried running them from my laptop without even configuring Reva or Wopi adresses and more than half of them passed, so I'm not sure if they are up to date. Also, I'm not sure how to even configure them correctly
> 
> In the link I provided you'll see that by default they run against local storage (and they're now integrated in the GitHub CI, see e.g. https://github.com/cs3org/wopiserver/runs/5394336262, so it's fair they pass. You should try and run them against Reva.
> 
> As for the version, yeah this was the latest at the time I started to update the charts, but better to push to a more recent one.

Ok so all I have to do is to configure this file, right:
https://github.com/cs3org/wopiserver/blob/master/test/wopiserver-test.conf

The [cs3] part is pretty self-explanatory but how do I configure the rest to use my wopi https://cs3mesh.softwaremind.com/wopi? Please bear in mind that im running tests from a machine outside the cluster.

**Comment by glpatcern** [comment]
> Ok so all I have to do is to configure this file, right:
> https://github.com/cs3org/wopiserver/blob/master/test/wopiserver-test.conf

Yes, and if you follow the steps you'll see that the test suite is there to validate the software (from a developer's perspective if I can say) and to make sure the connection to Reva works (i.e. the CS3APIs are aligned). It's not a "black-box" external test suite: to really validate the server you'll have to run the `reva open-in-app` command. But the charts PR is probably already ok to be merged.

**Pull request merged**
